### ISSUE TITLE
Parsing dbf file returns unexpected null values

### ISSUE THREAD

**Issue by mkfreeman** [mbostock/shapefile#70] opened 2022-02-07 21:31 UTC
The .dbf file downloaded [here](https://latfor.state.ny.us/maps/?sec=2022_congress) returns null values for each district. See [this notebook](https://observablehq.com/@observablehq/dbf-parsing-issue) for an example.

Other parsers (such as the one in R) detect values:
<img width="943" alt="Screen Shot 2022-02-07 at 4 21 13 PM" src="https://user-images.githubusercontent.com/1373882/152873946-5a1092dd-7ee0-439e-a74e-7a7ffa64307d.png">

@fil noted that:

> the file is full of \x00 then fails on !(value = value.trim()) || isNaN(value = +value) ? null : value; in the readNumber function. I guess we should trim the \x00 not only spaces

**Comment by Fil** [comment] 2022-02-07 22:09
I see \x00 everywhere in my shape files, not just in number fields. It's always a bit of pain to eradicate.

**Comment by Fil** [comment] 2022-02-08 08:51
duplicate of #68

**Comment by mbostock** [comment] 2022-02-08 16:51
Closing as duplicate.

**Closed as completed by mbostock** 2022-02-08 16:51 UTC
